// Generated by Xata Codegen 0.29.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Contacts",
    columns: [
      { name: "Name", type: "text", notNull: true, defaultValue: "" },
      {
        name: "EMail",
        type: "email",
        notNull: true,
        defaultValue: "dev@dev.com",
      },
      { name: "Message", type: "text", notNull: true, defaultValue: "" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Contacts = InferredTypes["Contacts"];
export type ContactsRecord = Contacts & XataRecord;

export type DatabaseSchema = {
  Contacts: ContactsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Andr-s-Izarra-s-workspace-r69703.eu-central-1.xata.sh/db/contact",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
